#version 450

#define W 8
#define MAX_B W*W*W


layout(std430, binding = 0) buffer VoxelTreeNode {
    uint blocks[MAX_B];
};

layout(std430, binding = 1) buffer AddedBlock { int addedX, addedY, addedZ; };

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// TODO:refactor
uint getBlockInd(int x, int y, int z) {
    return x + W * y + W * W * z;
}

void main()
{
    blocks[getBlockInd(addedX, addedY, addedZ)] = 1;
}