name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: musholic/plaxel:latest
      #- name: Collect coverage into one XML report
      #  if: always()
      #  run: gcovr --sonarqube > coverage.xml
      #- name: Run sonar-scanner
      #  if: always()
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #  run: |
      #    sonar-scanner \
      #      --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}" \
      #      --define sonar.coverageReportPaths=coverage.xml
      #- uses: actions/upload-artifact@v3
      #  if: always()
      #  with:
      #    name: test_report
      #    path: build/debug/test_report
      #    retention-days: 30
